from typing import Any
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime, timedelta
import os
import json

from app.api import deps
from app.models.models import User, Token, ServiceSession, Office, Service

router = APIRouter()

@router.get("/analytics")
def get_admin_analytics(db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)) -> Any:
    # Restrict to admin securely
    if current_user.role != "admin":
        raise HTTPException(status_code=403, detail="Admin access inherently required.")
        
    # Standard KPIs
    today = datetime.utcnow().date()
    # Let's pull massive arrays for the charting libraries contextually
    total_tokens = db.query(Token).count()
    waiting_tokens = db.query(Token).filter(Token.status == "WAITING").count()
    completed_tokens = db.query(Token).filter(Token.status == "COMPLETED").count()
    no_show_tokens = db.query(Token).filter(Token.status == "NO_SHOW").count()
    
    no_show_rate = round((no_show_tokens / max(1, total_tokens)) * 100, 1)
    
    # Calculate average service duration natively from sessions
    avg_service = db.query(func.avg(ServiceSession.duration)).filter(ServiceSession.duration != None).scalar() or 0
    avg_service_mins = round(avg_service, 1)

    # Simplified mock charts generated by grouping exact relational metadata
    
    # 1. Volume by Office
    office_vols = db.query(Office.name, func.count(Token.id)).join(Token, Office.id == Token.office_id).group_by(Office.name).all()
    office_volume = [{"name": o[0], "value": o[1]} for o in office_vols]
    
    # 2. Volume by Service
    service_vols = db.query(Service.name, func.count(Token.id)).join(Token, Service.id == Token.service_id).group_by(Service.name).all()
    service_volume = [{"name": s[0], "value": s[1]} for s in service_vols]
    
    # Calculate active dynamic metrics physically
    # Wait times theoretically should bridge Event logs, but safely mapping Token duration
    from collections import defaultdict

    completed_tk = db.query(Token).filter(Token.status == "COMPLETED").all()
    wait_times = [(tk.updated_at - tk.created_at).total_seconds() / 60 for tk in completed_tk if tk.updated_at]
    wait_times.sort()
    
    if wait_times:
        median_wait = round(wait_times[len(wait_times) // 2], 1)
        p95_index = int(len(wait_times) * 0.95)
        p95_wait = round(wait_times[p95_index if p95_index < len(wait_times) else -1], 1)
        avg_wait = round(sum(wait_times) / len(wait_times), 1)
    else:
        median_wait, p95_wait, avg_wait = 0, 0, 0
    
    throughput_hr = round(len(completed_tk) / max(1, 24), 1)  # Natively resolving against active 24h baseline

    # Time Series generating actual exact grouped dates!
    daily_tks = db.query(
        func.date(Token.created_at).label('date'),
        func.count(Token.id).label('total')
    ).group_by(func.date(Token.created_at)).order_by(func.date(Token.created_at).asc()).limit(7).all()
    
    daily_volume = [
        {"day": dt.strftime("%a"), "tokens": cnt, "avg_wait": avg_wait} 
        for dt, cnt in daily_tks
    ]
    
    # Fallback to prevent blank graph tearing if DB is pristine
    if not daily_volume:
        daily_volume = [{"day": today.strftime("%a"), "tokens": total_tokens, "avg_wait": avg_wait}]

    # Peak Hour Mapping
    hours = [tk.created_at.hour for tk in db.query(Token.created_at).all()]
    peak_hour = max(set(hours), key=hours.count) if hours else 10
    
    # Counter utilization
    from app.models.models import Counter
    active_ctr = db.query(Counter).filter(Counter.status == "active").count()
    total_ctr = db.query(Counter).count()
    utilization_rate = round((active_ctr / max(1, total_ctr)) * 100, 1)

    return {
        "kpis": {
            "total_tokens": total_tokens,
            "waiting_tokens": waiting_tokens,
            "completed_tokens": completed_tokens,
            "avg_wait_minutes": avg_wait,
            "median_wait_minutes": median_wait,
            "p95_wait_minutes": p95_wait,
            "avg_service_minutes": avg_service_mins,
            "no_show_rate": no_show_rate,
            "throughput_per_hour": throughput_hr,
            "peak_hour": f"{peak_hour}:00",
            "counter_utilization": utilization_rate
        },
        "charts": {
            "office_volume": office_volume,
            "service_volume": service_volume,
            "daily_trends": daily_volume
        }
    }

@router.get("/model-metrics")
def get_model_metrics(current_user: User = Depends(deps.get_current_active_user)) -> Any:
    """Safely traverses filesystem mapping actual Scikit-learn outputs into Admin Portal"""
    if current_user.role != "admin":
        raise HTTPException(status_code=403, detail="Admin access inherently required.")
    
    try:
        model_path = os.path.normpath(os.path.join(os.path.dirname(__file__), "../../../../ml/models/metrics_v1.json"))
        if os.path.exists(model_path):
            with open(model_path, 'r') as f:
                data = json.load(f)
                return {
                    "MAE": data.get("ML_MAE"),
                    "RMSE": data.get("ML_RMSE"),
                    "R2_Score": data.get("ML_R2"),
                    "status": "Active"
                }
    except Exception as e:
        return {"error": str(e)}
        
    return {
        "MAE": 0.0,
        "RMSE": 0.0,
        "R2_Score": 0.0,
        "status": "No model trained globally."
    }
