from typing import Any, List, Optional
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime, timedelta
import os
import json
from pydantic import BaseModel

from app.api import deps
from app.models.models import User, Token, ServiceSession, Office, Service

router = APIRouter()

# ── Shared schemas ────────────────────────────────────────────────────────────
class OfficeCreate(BaseModel):
    name: str
    city: str
    address: Optional[str] = None
    status: Optional[str] = "active"

class ServiceCreate(BaseModel):
    name: str
    code: str
    description: Optional[str] = None
    baseline_service_minutes: Optional[int] = 15
    status: Optional[str] = "active"
    office_id: int

class CounterCreate(BaseModel):
    office_id: int
    counter_name: str
    status: Optional[str] = "active"

class EmployeeUpdate(BaseModel):
    name: Optional[str] = None
    email: Optional[str] = None
    new_password: Optional[str] = None
    mobile_number: Optional[str] = None
    assigned_office_id: Optional[int] = None
    assigned_counter_id: Optional[int] = None
    status: Optional[str] = None

@router.get("/analytics")
def get_admin_analytics(db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)) -> Any:
    # Restrict to admin securely
    if current_user.role != "admin":
        raise HTTPException(status_code=403, detail="Admin access inherently required.")
        
    # Standard KPIs
    today = datetime.utcnow().date()
    # Let's pull massive arrays for the charting libraries contextually
    total_tokens = db.query(Token).count()
    waiting_tokens = db.query(Token).filter(Token.status == "WAITING").count()
    completed_tokens = db.query(Token).filter(Token.status == "COMPLETED").count()
    no_show_tokens = db.query(Token).filter(Token.status == "NO_SHOW").count()
    
    no_show_rate = round((no_show_tokens / max(1, total_tokens)) * 100, 1)
    
    # Calculate average service duration natively from sessions
    avg_service = db.query(func.avg(ServiceSession.duration)).filter(ServiceSession.duration != None).scalar() or 0
    avg_service_mins = round(avg_service, 1)

    # Simplified mock charts generated by grouping exact relational metadata
    
    # 1. Volume by Office
    office_vols = db.query(Office.name, func.count(Token.id)).join(Token, Office.id == Token.office_id).group_by(Office.name).all()
    office_volume = [{"name": o[0], "value": o[1]} for o in office_vols]
    
    # 2. Volume by Service
    service_vols = db.query(Service.name, func.count(Token.id)).join(Token, Service.id == Token.service_id).group_by(Service.name).all()
    service_volume = [{"name": s[0], "value": s[1]} for s in service_vols]
    
    # Calculate active dynamic metrics physically
    # Wait times theoretically should bridge Event logs, but safely mapping Token duration
    from collections import defaultdict

    completed_tk = db.query(Token).filter(Token.status == "COMPLETED").all()
    wait_times = []
    for tk in completed_tk:
        session = db.query(ServiceSession).filter(ServiceSession.token_id == tk.id).first()
        if session and session.started_at:
            wait_times.append((session.started_at - tk.created_at).total_seconds() / 60)
    wait_times.sort()
    
    if wait_times:
        median_wait = round(wait_times[len(wait_times) // 2], 1)
        p95_index = int(len(wait_times) * 0.95)
        p95_wait = round(wait_times[p95_index if p95_index < len(wait_times) else -1], 1)
        avg_wait = round(sum(wait_times) / len(wait_times), 1)
    else:
        median_wait, p95_wait, avg_wait = 0, 0, 0
    
    throughput_hr = round(len(completed_tk) / max(1, 24), 1)  # Natively resolving against active 24h baseline

    # Time Series padding last 7 days
    daily_tks = db.query(
        func.date(Token.created_at).label('date'),
        func.count(Token.id).label('total')
    ).group_by(func.date(Token.created_at)).all()
    
    daily_map = {dt: cnt for dt, cnt in daily_tks}
    
    daily_volume = []
    for i in range(6, -1, -1):
        d = today - timedelta(days=i)
        cnt = daily_map.get(d, 0)
        daily_volume.append({
            "day": d.strftime("%a"), 
            "tokens": cnt, 
            "avg_wait": avg_wait if cnt > 0 else 0
        })

    # Peak Hour Mapping
    hours = [tk.created_at.hour for tk in db.query(Token.created_at).all()]
    peak_hour = max(set(hours), key=hours.count) if hours else 10
    
    # Counter utilization
    from app.models.models import Counter
    active_ctr = db.query(Counter).filter(Counter.status == "active").count()
    total_ctr = db.query(Counter).count()
    utilization_rate = round((active_ctr / max(1, total_ctr)) * 100, 1)

    return {
        "kpis": {
            "total_tokens": total_tokens,
            "waiting_tokens": waiting_tokens,
            "completed_tokens": completed_tokens,
            "avg_wait_minutes": avg_wait,
            "median_wait_minutes": median_wait,
            "p95_wait_minutes": p95_wait,
            "avg_service_minutes": avg_service_mins,
            "no_show_rate": no_show_rate,
            "throughput_per_hour": throughput_hr,
            "peak_hour": f"{peak_hour}:00",
            "counter_utilization": utilization_rate
        },
        "charts": {
            "office_volume": office_volume,
            "service_volume": service_volume,
            "daily_trends": daily_volume
        }
    }

@router.get("/model-metrics")
def get_model_metrics(current_user: User = Depends(deps.get_current_active_user)) -> Any:
    """Safely traverses filesystem mapping actual Scikit-learn outputs into Admin Portal"""
    if current_user.role != "admin":
        raise HTTPException(status_code=403, detail="Admin access inherently required.")
    
    try:
        model_path = os.path.normpath(os.path.join(os.path.dirname(__file__), "../../../../ml/models/metrics_v1.json"))
        if os.path.exists(model_path):
            with open(model_path, 'r') as f:
                data = json.load(f)
                return {
                    "MAE": data.get("ML_MAE"),
                    "RMSE": data.get("ML_RMSE"),
                    "R2_Score": data.get("ML_R2"),
                    "status": "Active"
                }
    except Exception as e:
        return {"error": str(e)}
        
    return {
        "MAE": 0.0,
        "RMSE": 0.0,
        "R2_Score": 0.0,
        "status": "No model trained globally."
    }

# ── OFFICES ───────────────────────────────────────────────────────────────────
@router.get("/offices")
def get_admin_offices(db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    return db.query(Office).all()

@router.post("/offices")
def create_admin_office(office: OfficeCreate, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    if not office.name.strip() or not office.city.strip():
        raise HTTPException(status_code=422, detail="Name and city are required.")
    db_office = Office(**office.dict())
    db.add(db_office)
    db.commit()
    db.refresh(db_office)
    return db_office

@router.put("/offices/{office_id}")
def update_admin_office(office_id: int, office: OfficeCreate, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    if not office.name.strip() or not office.city.strip():
        raise HTTPException(status_code=422, detail="Name and city are required.")
    db_office = db.query(Office).filter(Office.id == office_id).first()
    if not db_office: raise HTTPException(status_code=404, detail="Office not found")
    for k, v in office.dict().items(): setattr(db_office, k, v)
    db.commit()
    db.refresh(db_office)
    return db_office

@router.delete("/offices/{office_id}")
def delete_admin_office(office_id: int, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    db_office = db.query(Office).filter(Office.id == office_id).first()
    if not db_office: raise HTTPException(status_code=404, detail="Office not found")
    # Safety: prevent deletion if tokens exist
    token_count = db.query(Token).filter(Token.office_id == office_id).count()
    if token_count > 0:
        raise HTTPException(status_code=400, detail=f"Cannot delete: {token_count} tokens are linked to this office.")
    db.delete(db_office)
    db.commit()
    return {"success": True, "message": "Office deleted successfully."}

# ── SERVICES ──────────────────────────────────────────────────────────────────
@router.get("/services")
def get_admin_services(db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    return db.query(Service).all()

@router.post("/services")
def create_admin_service(service: ServiceCreate, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    if not service.name.strip() or not service.code.strip():
        raise HTTPException(status_code=422, detail="Name and code are required.")
    from app.models.models import OfficeService
    db_service = Service(name=service.name, code=service.code, description=service.description,
                         baseline_service_minutes=service.baseline_service_minutes, status=service.status)
    db.add(db_service)
    db.flush()
    oserv = OfficeService(office_id=service.office_id, service_id=db_service.id)
    db.add(oserv)
    db.commit()
    db.refresh(db_service)
    return db_service

@router.put("/services/{service_id}")
def update_admin_service(service_id: int, service: ServiceCreate, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    if not service.name.strip() or not service.code.strip():
        raise HTTPException(status_code=422, detail="Name and code are required.")
    db_service = db.query(Service).filter(Service.id == service_id).first()
    if not db_service: raise HTTPException(status_code=404, detail="Service not found")
    db_service.name = service.name
    db_service.code = service.code
    db_service.description = service.description
    db_service.baseline_service_minutes = service.baseline_service_minutes
    db_service.status = service.status
    db.commit()
    db.refresh(db_service)
    return db_service

@router.delete("/services/{service_id}")
def delete_admin_service(service_id: int, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    db_service = db.query(Service).filter(Service.id == service_id).first()
    if not db_service: raise HTTPException(status_code=404, detail="Service not found")
    token_count = db.query(Token).filter(Token.service_id == service_id).count()
    if token_count > 0:
        raise HTTPException(status_code=400, detail=f"Cannot delete: {token_count} tokens are linked to this service.")
    db.delete(db_service)
    db.commit()
    return {"success": True, "message": "Service deleted successfully."}

# ── COUNTERS ──────────────────────────────────────────────────────────────────
@router.get("/counters")
def get_admin_counters(db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    from app.models.models import Counter
    counters = db.query(Counter).all()
    res = []
    for c in counters:
        o = db.query(Office).filter(Office.id == c.office_id).first()
        # Get assigned employee if any
        emp = db.query(User).filter(User.assigned_counter_id == c.id, User.role == "employee").first()
        res.append({
            "id": c.id, "counter_name": c.counter_name, "office_id": c.office_id,
            "status": c.status, "office_name": o.name if o else "Unknown",
            "employee_name": emp.name if emp else None, "employee_email": emp.email if emp else None
        })
    return res

@router.post("/counters")
def create_admin_counter(counter: CounterCreate, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    if not counter.counter_name.strip():
        raise HTTPException(status_code=422, detail="Counter name is required.")
    from app.models.models import Counter
    c = Counter(**counter.dict())
    db.add(c)
    db.commit()
    db.refresh(c)
    return c

@router.put("/counters/{counter_id}")
def update_admin_counter(counter_id: int, counter: CounterCreate, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    if not counter.counter_name.strip():
        raise HTTPException(status_code=422, detail="Counter name is required.")
    from app.models.models import Counter
    db_counter = db.query(Counter).filter(Counter.id == counter_id).first()
    if not db_counter: raise HTTPException(status_code=404, detail="Counter not found")
    for k, v in counter.dict().items(): setattr(db_counter, k, v)
    db.commit()
    db.refresh(db_counter)
    return db_counter

@router.delete("/counters/{counter_id}")
def delete_admin_counter(counter_id: int, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    from app.models.models import Counter
    db_counter = db.query(Counter).filter(Counter.id == counter_id).first()
    if not db_counter: raise HTTPException(status_code=404, detail="Counter not found")
    # Un-assign any employees linked to this counter
    db.query(User).filter(User.assigned_counter_id == counter_id).update({"assigned_counter_id": None, "assigned_office_id": None})
    db.delete(db_counter)
    db.commit()
    return {"success": True, "message": "Counter deleted successfully."}

# ── EMPLOYEES ─────────────────────────────────────────────────────────────────
@router.get("/employees")
def get_admin_employees(db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    from app.models.models import Counter
    employees = db.query(User).filter(User.role == "employee").all()
    res = []
    for emp in employees:
        office = db.query(Office).filter(Office.id == emp.assigned_office_id).first() if emp.assigned_office_id else None
        counter = db.query(Counter).filter(Counter.id == emp.assigned_counter_id).first() if emp.assigned_counter_id else None
        res.append({
            "id": emp.id, "name": emp.name, "email": emp.email,
            "mobile_number": emp.mobile_number, "status": emp.status,
            "assigned_office_id": emp.assigned_office_id,
            "assigned_office_name": office.name if office else None,
            "assigned_counter_id": emp.assigned_counter_id,
            "assigned_counter_name": counter.counter_name if counter else None,
        })
    return res

@router.put("/employees/{employee_id}")
def update_admin_employee(employee_id: int, data: EmployeeUpdate, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    from app.core import security
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    emp = db.query(User).filter(User.id == employee_id, User.role == "employee").first()
    if not emp: raise HTTPException(status_code=404, detail="Employee not found")
    
    update_data = data.dict(exclude_unset=True)
    if "email" in update_data and update_data["email"]:
        new_email = update_data["email"].strip().lower()
        if new_email != emp.email.lower():
            existing = db.query(User).filter(func.lower(User.email) == new_email, User.id != employee_id).first()
            if existing:
                raise HTTPException(status_code=400, detail="Email already in use by another account.")
            emp.email = new_email
        update_data.pop("email", None)

    if "name" in update_data and update_data["name"]:
        emp.name = update_data["name"].strip()
        update_data.pop("name", None)

    if "new_password" in update_data:
        pwd = update_data.pop("new_password")
        if pwd and pwd.strip():
            emp.password_hash = security.get_password_hash(pwd.strip())
            
    for k, v in update_data.items():
        setattr(emp, k, v)
    db.commit()
    db.refresh(emp)
    return {"success": True, "message": "Employee updated successfully."}

@router.delete("/employees/{employee_id}")
def delete_admin_employee(employee_id: int, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    emp = db.query(User).filter(User.id == employee_id, User.role == "employee").first()
    if not emp: raise HTTPException(status_code=404, detail="Employee not found")
    db.delete(emp)
    db.commit()
    return {"success": True, "message": "Employee deleted successfully."}

# ── TOKENS ────────────────────────────────────────────────────────────────────
@router.get("/tokens")
def get_admin_tokens(db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    from app.services.queue_manager import QueueManager
    from app.schemas.prediction import WaitTimeRequest
    from app.services.prediction_engine import PredictionEngine
    tokens = db.query(Token).order_by(Token.created_at.desc()).limit(200).all()
    res = []
    for t in tokens:
        o = db.query(Office).filter(Office.id == t.office_id).first()
        s = db.query(Service).filter(Service.id == t.service_id).first()
        pos = None
        est = None
        if t.status in ["WAITING", "CALLED"]:
            try:
                stats = QueueManager.get_queue_stats(db, t.office_id, t.service_id, t.id)
                pos = stats["queue_position"]
                req = WaitTimeRequest(office_id=t.office_id, service_id=t.service_id, token_id=t.id, people_ahead=stats["people_ahead"])
                pred = PredictionEngine.get_wait_time(db, req)
                est = pred["predicted_wait_minutes"]
            except Exception:
                pass
        res.append({
            "id": t.id, "token_number": t.token_number, "status": t.status,
            "created_at": t.created_at,
            "office_id": t.office_id,
            "service_id": t.service_id,
            "office_name": o.name if o else "Unknown",
            "service_name": s.name if s else "Unknown",
            "position": pos, "estimated_wait": est
        })
    return res

@router.delete("/tokens/{token_id}")
def delete_admin_token(token_id: int, db: Session = Depends(deps.get_db), current_user: User = Depends(deps.get_current_active_user)):
    if current_user.role != "admin": raise HTTPException(status_code=403, detail="Admin only")
    token = db.query(Token).filter(Token.id == token_id).first()
    if not token: raise HTTPException(status_code=404, detail="Token not found")
    token.status = "CANCELLED"
    db.commit()
    return {"success": True, "message": f"Token {token.token_number} cancelled."}
